# Configuration

loader:
  paths: 
    - "/Users/David/Downloads/Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks.pdf"

splitter:
  method: "recursive"
  chunk_size: 256
  chunk_overlap: 128

database:
  path: "data/db"

pipelines:
  openai:
    embedding: "text-embedding-3-small"
    llm: "gpt-3.5-turbo"

  local:
    embedding: "sentence-transformer"
    llm: "llama3"

output:
  directory: "data/results"